### ISSUE TITLE
Using the library in TypeScript

### ISSUE THREAD

**Issue by bartosz-maciaszek** [DaddyWarbucks/static-google-map#5]
Hey! How do I use it in TypeScript? Typings don't seem to export the `staticMapUrl` function. 

```
Module '"static-google-map"' has no exported member 'staticMapUrl'.

1 import { staticMapUrl } from 'static-google-map';
           ~~~~~~~~~~~~
```

**Comment by DaddyWarbucks** [comment]
You are right. This was forked from the awesome https://github.com/bondz/react-static-google-map and it looks like I failed to update the typings. I don't use TS much, so that must have slipped my mind. I am swamped with work at the moment, but if you are willing to open a PR I would be happy to review an merge it.

**Comment by alubeck** [comment]
Hi, I made a PR https://github.com/DaddyWarbucks/static-google-map/pull/6 to tackle this issue. In the meantime you could just superficially type the library in your codebase on your own.

```typescript
// your-static-google-map.d.ts

declare module 'static-google-map' {
  export function staticMapUrl(props: any): string;
}
```
